// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsckvvperdjoobyptnnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzY2t2dnBlcmRqb29ieXB0bm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzI1NzMsImV4cCI6MjA1NzgwODU3M30.WQD8jhbk3XWa0CxM6gHvfZ57h68gQOCOrgJ6lnW5maw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);